version: '3'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_main
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=application
      - MYSQL_PASSWORD=application
      - MYSQL_DATABASE=hhplus
    volumes:
      - ./data/mysql/:/var/lib/mysql
    networks:
      - app-network

  mysql_test:
    image: mysql:8.0
    container_name: mysql_test
    ports:
      - "3307:3307"  # 테스트 DB의 포트를 3307로 설정 (메인과 충돌 방지)
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=test_user
      - MYSQL_PASSWORD=test_passwordd
      - MYSQL_DATABASE=hhplus_test  # 테스트용 DB 이름
    volumes:
      - ./data/mysql_test/:/var/lib/mysql
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    command: [ "redis-server", "--appendonly", "yes" ] # AOF 영속성 활성화
    networks:
      - app-network


  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - app-network

  kafka:
    image: wurstmeister/kafka:2.12-2.5.0
    container_name: kafka
    ports:
      - "9092:9092"
      - "29092:29092"  # 외부에서 접근할 수 있도록 추가
    environment:
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app-network

networks:
  app-network:
    driver: bridge